services:
  server:
    image: novadityap/public-complaint-app-server-dev
    container_name: public-complaint-app-server-dev
    build:
      context: ./server
      dockerfile: Dockerfile
    command: php artisan serve --host=0.0.0.0
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./server:/app
    networks:
      - public-complaint-app-dev

  client:
    image: novadityap/public-complaint-app-client-dev
    container_name: public-complaint-app-client-dev
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm run dev
    env_file:
      - ./client/.env.development
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./client:/app
    networks:
      - public-complaint-app-dev

  postgres:
    container_name: public-complaint-app-postgres-dev
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - public-complaint-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: public_complaint_app_dev
    networks:
      - public-complaint-app-dev

volumes:
  public-complaint-postgres-data:
    name: public-complaint-postgres-data
networks:
  public-complaint-app-dev:
    name: public-complaint-app-dev
